prefix: SYSU
fp16: True

# dataset
sample_method: identity_uniform #identity_uniform #identity_random
image_size: (384, 128) # (384, 144) # (256, 128) #(384, 144)
p_size: 8
k_size: 4

dataset: sysu

# loss
bg_kl: true
sm_kl: true
decompose: true
distalign: true
IP: true
classification: true
center_cluster: false
triplet: true
center: false
fb_dt: false

# attetion
attn_guidance: True
attn_weight: 0.2

# parameters
margin: 0.3 # 1.3
# pattern attention
num_parts: 6
weight_sep: 0.1 #0.5
# mutual learning
update_rate: 0.2
weight_sid: 0.8 #0.5
weight_KL: 0.6 #2.5

# architecture
drop_last_stride: true
pattern_attention: false
mutual_learning: false
modality_attention: 0

# optimizer
lr: 0.00035
optimizer: adam
num_epoch: 400 # 160
lr_step: [100, 160] # [60, 100] # [40, 70]

# Early stopping
early_stopping_patience: 10 
scheduler_type: cosine   

# augmentation
random_flip: true
random_crop: true
random_erase: true
color_jitter: true
padding: 10

# log
log_period: 150
start_eval: 100
eval_interval: 5
rerank: True
