prefix: SYSU
fp16: True

# dataset
sample_method: identity_random #identity_uniform #identity_random
image_size: (384, 144) #(384, 144)
p_size: 4
k_size: 4

dataset: sysu

# loss
bg_kl: true
sm_kl: true
decompose: true
distalign: true
IP: true
classification: true
center_cluster: false
triplet: true
center: false
fb_dt: false

# parameters
margin: 1.3
# pattern attention
num_parts: 6
weight_sep: 0.5
# mutual learning
update_rate: 0.2
weight_sid: 0.5
weight_KL: 2.5

# architecture
drop_last_stride: true
pattern_attention: false
mutual_learning: false
modality_attention: 0

# optimizer
lr: 0.005
optimizer: sgd
num_epoch: 120
lr_step: [40, 70]

# Early stopping
early_stopping_patience: 4 
scheduler_type: 'cosine'   

# augmentation
random_flip: true
random_crop: true
random_erase: true
color_jitter: true
padding: 10

# log
log_period: 150
start_eval: 20
eval_interval: 5
rerank: False
